apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: configstore
spec:
  type: configuration.redis
  metadata:
  - name: redisHost
    value: localhost:6379
  #- name: redisPassword
  #  value: <PASSWORD>
  #replicas: 1
  #selector:
  #  matchLabels:
  #    app: node
  #template:
  #  metadata:
  #    labels:
  #      app: node
  #    annotations:
  #      dapr.io/enabled: "true"
  #      dapr.io/app-id: "nodeapp"
  #      dapr.io/app-port: "3000"
  #      dapr.io/config: "featureconfig"